apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketpulse-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketpulse-backend
  template:
    metadata:
      labels:
        app: marketpulse-backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/gen-lang-client-0448429144/marketpulse-repo/marketpulse-backend:latest
        ports:
        - containerPort: 8000
